import { defineConfig } from "vitepress";

const SITE_DESCRIPTION =
  "Type-safe dependency injection for TypeScript: a container holds your services' domain and provides it. Requirements and construction errors are tracked in the type system. The wiring sibling of unthrown.";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "demesne",
  description: SITE_DESCRIPTION,
  base: "/demesne/",
  lang: "en-US",
  cleanUrls: true,

  // The API reference under /api/ is generated by TypeDoc and copied in at build
  // time; its cross-references use relative links TypeDoc resolves itself.
  ignoreDeadLinks: [/^\/api\//, /^\.\/index$/, /^\.\/[a-z-]+$/, /^\.\.\//],

  sitemap: {
    hostname: "https://btravstack.github.io/demesne/",
  },

  themeConfig: {
    logo: { light: "/logo-light.svg", dark: "/logo-dark.svg" },

    nav: [
      { text: "Guide", link: "/guide/why-demesne" },
      { text: "API", link: "/api/" },
      {
        text: "Changelog",
        link: "https://github.com/btravstack/demesne/releases",
      },
      // Back to the btravstack hub (links the docs up to the landing page).
      { text: "btravstack", link: "https://btravstack.github.io/" },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Why demesne?", link: "/guide/why-demesne" },
            { text: "Comparison", link: "/guide/comparison" },
            { text: "Getting Started", link: "/guide/getting-started" },
            { text: "Core Concepts", link: "/guide/core-concepts" },
          ],
        },
        {
          text: "Building Graphs",
          items: [
            { text: "Layers & Wiring", link: "/guide/layers-and-wiring" },
            { text: "Errors at the Edge", link: "/guide/errors-at-the-edge" },
            { text: "Configuration", link: "/guide/configuration" },
          ],
        },
        {
          text: "Architecture",
          items: [
            { text: "Clean Architecture", link: "/guide/clean-architecture" },
            { text: "Resources & Scopes", link: "/guide/resources-and-scopes" },
            { text: "Contract Workers", link: "/guide/contract-workers" },
          ],
        },
      ],
      "/api/": [
        {
          text: "API Reference",
          items: [
            { text: "Overview", link: "/api/" },
            { text: "demesne", link: "/api/core/" },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/btravstack/demesne" },
      { icon: "npm", link: "https://www.npmjs.com/package/demesne" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: `Copyright © ${new Date().getFullYear()} Benoit TRAVERS`,
    },

    search: {
      provider: "local",
    },

    editLink: {
      pattern: "https://github.com/btravstack/demesne/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },

  vite: {
    // @btravstack/theme's entry imports `vitepress/theme` (which pulls in `.css`)
    // and its own `style.css`. VitePress externalizes node_modules deps in the SSR
    // build, so Node's ESM loader would hit those `.css` files and throw
    // ERR_UNKNOWN_FILE_EXTENSION. Bundling the theme through Vite handles the CSS.
    ssr: { noExternal: ["@btravstack/theme"] },
  },

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/demesne/logo.svg" }],
    ["meta", { name: "author", content: "Benoit TRAVERS" }],
    ["meta", { name: "robots", content: "index, follow" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "typescript, dependency injection, di, ioc, inversion of control, type-safe, context, layer, container, hexagonal, ddd, unthrown",
      },
    ],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "demesne" }],
    ["meta", { property: "og:title", content: "demesne" }],
    ["meta", { property: "og:description", content: SITE_DESCRIPTION }],
    [
      "meta",
      { property: "og:image", content: "https://btravstack.github.io/demesne/og-demesne.png" },
    ],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    [
      "meta",
      { name: "twitter:image", content: "https://btravstack.github.io/demesne/og-demesne.png" },
    ],
  ],
});
